### ISSUE TITLE
Rewrite code to use parser = argparse.ArgumentParser [zenodo-cli]

### ISSUE THREAD

**Issue by bjohas** [bjohas/Zenodo-tools#2]
My preference is to retain the 'verb' structure, e.g.
```
zenodo-cli create
```
without "--".

The current options are
```
zenodo-cli get deposit_id
zenodo-cli create file1.json [file2.json [file3.json ...]]")
zenodo-cli duplicate original_deposit_id [title]")
zenodo-cli upload bucketurl file.pdf
zenodo-cli copy original_deposit_id file1.pdf [file2.pdf [file3.pdf ...]]"
zenodo-cli adapt original_deposit_id title date file1.pdf
```
They should be modified (with help text added) as follows:
```
zenodo-cli get id1 [id2 ...]
```
See issue: https://github.com/bjohas/Zenodo-tools/issues/4
```
zenodo-cli create file1.json [file2.json [file3.json ...]]")
```
Add: Helptext: The `create` command creates new records based on the json files. provided. 
```
zenodo-cli duplicate original_deposit_id [title]")
```
See https://github.com/bjohas/Zenodo-tools/issues/5
```
zenodo-cli upload bucketurl file.pdf
```
See https://github.com/bjohas/Zenodo-tools/issues/6

This option
```
zenodo-cli copy original_deposit_id file1.pdf [file2.pdf [file3.pdf ...]]
```
should be renamed to 
```
zenodo-cli multicopy original_deposit_id file1.pdf [file2.pdf [file3.pdf ...]]
```
but otherwise remain unchanged.

For option 
```
zenodo-cli adapt original_deposit_id title date file1.pdf
```
see  https://github.com/bjohas/Zenodo-tools/issues/7

**Comment by a1diablo** [comment]
Unfortunately, argparse does not allow command arguments without -- (dashes) as prefix. I checked but there is no other sophisticated clear cut way to do so. What do you suggest?

**Comment by bjohas** [comment]
Could you do this in the same way as this https://github.com/edtechhub/gtasks ?
