### ISSUE TITLE
Extend the script zenodo-cli get id1 [id2 ...]

### ISSUE THREAD

**Issue by bjohas** [bjohas/Zenodo-tools#4]
Adjust this so that zenodo-cli getsmutiple ids, and that these are exported to json files one by one.

The id can be provided in the following formats
```
123
https://zenodo.org/deposit/123
https://zenodo.org/record/123
```
The simplest thing would be to just allow any string as an id, as long as that string ends in a sequence of numbers. See https://github.com/bjohas/Zenodo-tools/issues/10

Adjust helptext:
```
zenodo-cli get id1 [id2 ...]
```
Helptext: The `get` command gets the ids listed, and writes these out to id1.json, id2.json etc. The id can be provided as a number, as a deposit URL or record URL.

This command should take an additional option --publish/--open as described in https://github.com/bjohas/Zenodo-tools/issues/8.

**Comment by a1diablo** [comment]
Pushed the requested changes.
